### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by JuanMaoForLuo** [smileCH/RangeBar#1]
你好开发者，我在郭霖博客中看到您的开源库，觉得非常棒，但在使用您的开源项目时，发现了一些问题，导致我无法使用，具体bug为 当价格区间比较大时，例如0-7000 ，步长为50，布局中有padding, 滑动滑块时, --->1: 左右拖动滑块，基本划不到0元的位置，都在在200以上的位置，（价格小时又不会，比如0-400）

2：有padding时，最大值为7000，步长为50，-->滑块还没到横向进度条的最右侧就显示到了7000的位置。
如果这个bug,能解决,我觉得将是个很不错的控件

**Comment by smileCH** [comment]
您好，非常感谢老铁提出的问题，我会抽个时间修复下，有问题欢迎提出来

**Comment by juesai2015** [comment]
一楼的问题你看看在 RangeBarView 中把 getSliceByCoordinate() 这个函数中的代码用下面的替换一下试试
 private int getSliceByCoordinate(int moveDistance){
        //此位置坐标对应的距离能分多少份
//        int parts = moveDistance / perSlice;//总距离 / 每一份的距离  
//        Log.e("TAG", "左边-----> part："+ parts);
//        parts = moveDistance % perSlice >= perSlice/2 ? parts + 1 : parts;
//        Log.e("TAG", "左边-----> moveDistance："+ moveDistance);
//        Log.e("TAG", "左边-----> perSlice："+ perSlice);
//        Log.e("TAG", "左边-----> parts："+ parts);
//        return parts > slice ? slice : parts;
//

        if (moveDistance<(getPaddingLeft() + strokeRadius)){
            return 0;
        }

        //此位置坐标对应的距离能分多少份
        int parts = (moveDistance -(getPaddingLeft() + strokeRadius)) / perSlice;//总距离 / 每一份的距离  136/85 = 1.6
        parts = (moveDistance -(getPaddingLeft() + strokeRadius)) % perSlice >= perSlice/2 ? parts + 1 : parts;
        Log.e("TAG", "左边-----> moveDistance："+ moveDistance);
        Log.e("TAG", "左边-----> perSlice："+ perSlice);
        Log.e("TAG", "左边-----> leftPoint："+ (getPaddingLeft() + strokeRadius));
        Log.e("TAG", "左边-----> parts："+ parts);
        return parts > slice ? slice : parts;
    }

**Comment by juesai2015** [comment]
private int getSliceByCoordinate(int moveDistance){
        //此位置坐标对应的距离能分多少份
        /*
        int parts = moveDistance / perSlice;//总距离 / 每一份的距离  136/85 = 1.6
        Log.e("TAG", "左边-----> part："+ parts);
        parts = moveDistance % perSlice >= perSlice/2 ? parts + 1 : parts;
        Log.e("TAG", "左边-----> moveDistance："+ moveDistance);
        Log.e("TAG", "左边-----> perSlice："+ perSlice);
        Log.e("TAG", "左边-----> parts："+ parts);
        return parts > slice ? slice : parts;
        */

        if (moveDistance<(getPaddingLeft() + strokeRadius)){
            return 0;
        }
        //此位置坐标对应的距离能分多少份
        int parts = (moveDistance -(getPaddingLeft() + strokeRadius)) / perSlice;//总距离 / 每一份的距离  136/85 = 1.6
        parts = (moveDistance -(getPaddingLeft() + strokeRadius)) % perSlice >= perSlice/2 ? parts + 1 : parts;
        Log.e("TAG", "左边-----> moveDistance："+ moveDistance);
        Log.e("TAG", "左边-----> perSlice："+ perSlice);
        Log.e("TAG", "左边-----> leftPoint："+ (getPaddingLeft() + strokeRadius));
        Log.e("TAG", "左边-----> parts："+ parts);
        return parts > slice ? slice : parts;
    }

**Comment by juesai2015** [comment]
> 你好开发者，我在郭霖博客中看到您的开源库，觉得非常棒，但在使用您的开源项目时，发现了一些问题，导致我无法使用，具体bug为 当价格区间比较大时，例如0-7000 ，步长为50，布局中有padding, 滑动滑块时, --->1: 左右拖动滑块，基本划不到0元的位置，都在在200以上的位置，（价格小时又不会，比如0-400）
> 
> 2：有padding时，最大值为7000，步长为50，-->滑块还没到横向进度条的最右侧就显示到了7000的位置。
> 如果这个bug,能解决,我觉得将是个很不错的控件

// 在 RangeBarView 中把 getSliceByCoordinate() 这个函数中的代码用下面的替换一下试试
    /*
    private int getSliceByCoordinate(int moveDistance) {
        //此位置坐标对应的距离能分多少份

        int parts = moveDistance / perSlice;//总距离 / 每一份的距离  136/85 = 1.6
        Log.e("TAG", "左边-----> part："+ parts);
        parts = moveDistance % perSlice >= perSlice/2 ? parts + 1 : parts;
        Log.e("TAG", "左边-----> moveDistance："+ moveDistance);
        Log.e("TAG", "左边-----> perSlice："+ perSlice);
        Log.e("TAG", "左边-----> parts："+ parts);
        return parts > slice ? slice : parts;
    }

    */

    private int getSliceByCoordinate(int moveDistance) {

        if (moveDistance<(getPaddingLeft() + strokeRadius)){
            return 0;
        }
        //此位置坐标对应的距离能分多少份
        int parts = (moveDistance -(getPaddingLeft() + strokeRadius)) / perSlice;//总距离 / 每一份的距离  136/85 = 1.6
        parts = (moveDistance -(getPaddingLeft() + strokeRadius)) % perSlice >= perSlice/2 ? parts + 1 : parts;
        Log.e("TAG", "左边-----> moveDistance："+ moveDistance);
        Log.e("TAG", "左边-----> perSlice："+ perSlice);
        Log.e("TAG", "左边-----> leftPoint："+ (getPaddingLeft() + strokeRadius));
        Log.e("TAG", "左边-----> parts："+ parts);
        return parts > slice ? slice : parts;
    }

**Comment by juesai2015** [comment]
//     在 RangeBarView 中把 getSliceByCoordinate() 这个函数中的代码用下面的替换一下试试

//    private int getSliceByCoordinate(int moveDistance) {
//        此位置坐标对应的距离能分多少份
//
//        int parts = moveDistance / perSlice;//总距离 / 每一份的距离  136/85 = 1.6
//        Log.e("TAG", "左边-----> part："+ parts);
//        parts = moveDistance % perSlice >= perSlice/2 ? parts + 1 : parts;
//        Log.e("TAG", "左边-----> moveDistance："+ moveDistance);
//        Log.e("TAG", "左边-----> perSlice："+ perSlice);
//        Log.e("TAG", "左边-----> parts："+ parts);
//        return parts > slice ? slice : parts;
//    }
    

    private int getSliceByCoordinate(int moveDistance) {

        if (moveDistance<(getPaddingLeft() + strokeRadius)){
            return 0;
        }
        //此位置坐标对应的距离能分多少份
        int parts = (moveDistance -(getPaddingLeft() + strokeRadius)) / perSlice;//总距离 / 每一份的距离  
        parts = (moveDistance -(getPaddingLeft() + strokeRadius)) % perSlice >= perSlice/2 ? parts + 1 : parts;
        Log.e("TAG", "左边-----> moveDistance："+ moveDistance);
        Log.e("TAG", "左边-----> perSlice："+ perSlice);
        Log.e("TAG", "左边-----> leftPoint："+ (getPaddingLeft() + strokeRadius));
        Log.e("TAG", "左边-----> parts："+ parts);
        return parts > slice ? slice : parts;
    }

**Comment by JuanMaoForLuo** [comment]
你好 嘗試了您的解決方案 第一個bug已經被修復了，接著還有一個bug我提一下 ，可能因為您在代碼中沒有對右邊的小圓圈加上getPaddingRight() 計算位置的原因 ，當我的max比較大，step比較小時 ，xml中又對佈局設置了paddingRgiht() = 10dp，運行后滑動右側的小圓圈后 ，它就無法回到最大值，感謝您的開源 ，已star ,

**Comment by smileCH** [comment]
你们说的这些问题，我昨天看到后抽了个时间已经修复并上传了，并且我把修复的地方特别注释了日期以及这样改的目的，方便大家对照理解。目前感觉商用是没啥问题的，大家可以放心使用了。考虑到有的老铁可能只需要单项的滑动，所以后期打算做成可以根据用户的选择来决定是使用双向滑动还是单项滑动，只需要在application中初始化的时候告诉我你要使用哪种方式就行，这样才更灵活
